-- 01_combine_pharmacies.sql (BigQuery)
-- Builds INTERMEDIATE.PHARMACIES_COMBINED from eight RAW medical-aid network tables.
-- Municipality and city columns stay NULL pending geocoding verification.
-- Contract: PHARMACY_ID, PROVINCE, LOCAL_MUNICIPALITY, DISTRICT_MUNICIPALITY,
--           METROPOLITAN_MUNICIPALITY, CITY, PRACTICE_NAME, PRACTICE_NUM,
--           PRACTICE_TYPE, ADDRESS, PHONE, FUNDING, COMPANY, COORDS (GEOGRAPHY)

CREATE OR REPLACE TABLE INTERMEDIATE.PHARMACIES_COMBINED AS

-- GEMS GAUTENG: CITY and SUBURB folded into ADDRESS for geocoding context
SELECT
    'Gauteng' AS PROVINCE,
    CAST(NULL AS STRING) AS LOCAL_MUNICIPALITY,
    CAST(NULL AS STRING) AS DISTRICT_MUNICIPALITY,
    CAST(NULL AS STRING) AS METROPOLITAN_MUNICIPALITY,
    CAST(NULL AS STRING) AS CITY,
    INITCAP(TRIM(PRACTICE_NAME)) AS PRACTICE_NAME,
    TRIM(PRACTICE_NUM) AS PRACTICE_NUM,
    'Pharmacy' AS PRACTICE_TYPE,
    INITCAP(TRIM(ARRAY_TO_STRING(
        [NULLIF(TRIM(ADDRESS), ''), NULLIF(TRIM(SUBURB), ''), NULLIF(TRIM(CITY), '')],
        ', '
    ))) AS ADDRESS,
    TRIM(PHONE) AS PHONE,
    'Private' AS FUNDING,
    'GEMS' AS COMPANY,
    CAST(NULL AS GEOGRAPHY) AS COORDS
FROM RAW.PHARMACIES_GEMS_GAUTENG
WHERE PRACTICE_NAME IS NOT NULL
  AND TRIM(PRACTICE_NAME) != ''

UNION ALL

-- GEMS KZN
SELECT
    'Kwazulu-Natal',
    NULL, NULL, NULL, NULL,
    INITCAP(TRIM(PRACTICE_NAME)),
    TRIM(PRACTICE_NUM),
    'Pharmacy',
    INITCAP(TRIM(ARRAY_TO_STRING(
        [NULLIF(TRIM(ADDRESS), ''), NULLIF(TRIM(SUBURB), ''), NULLIF(TRIM(CITY), '')],
        ', '
    ))),
    TRIM(PHONE),
    'Private',
    'GEMS',
    NULL
FROM RAW.PHARMACIES_GEMS_KZN
WHERE PRACTICE_NAME IS NOT NULL
  AND TRIM(PRACTICE_NAME) != ''

UNION ALL

-- MOMENTUM GAUTENG: ADDRESS has building/shop info; STREET, AREA, POSTAL appended
SELECT
    'Gauteng',
    NULL, NULL, NULL, NULL,
    INITCAP(TRIM(PRACTICE_NAME)),
    NULL,
    'Pharmacy',
    INITCAP(TRIM(ARRAY_TO_STRING(
        [NULLIF(TRIM(ADDRESS), ''), NULLIF(TRIM(STREET), ''),
         NULLIF(TRIM(AREA), ''), NULLIF(TRIM(POSTAL), '')],
        ', '
    ))),
    TRIM(PHONE),
    'Private',
    'Momentum',
    NULL
FROM RAW.PHARMACIES_MOMENTUM_GAUTENG
WHERE PRACTICE_NAME IS NOT NULL
  AND TRIM(PRACTICE_NAME) != ''
  AND UPPER(TRIM(PRACTICE_NAME)) != 'PRACTICE_NAME'

UNION ALL

-- MOMENTUM KZN
SELECT
    'Kwazulu-Natal',
    NULL, NULL, NULL, NULL,
    INITCAP(TRIM(PRACTICE_NAME)),
    NULL,
    'Pharmacy',
    INITCAP(TRIM(ARRAY_TO_STRING(
        [NULLIF(TRIM(ADDRESS), ''), NULLIF(TRIM(STREET), ''),
         NULLIF(TRIM(AREA), ''), NULLIF(TRIM(POSTAL), '')],
        ', '
    ))),
    TRIM(PHONE),
    'Private',
    'Momentum',
    NULL
FROM RAW.PHARMACIES_MOMENTUM_KZN
WHERE PRACTICE_NAME IS NOT NULL
  AND TRIM(PRACTICE_NAME) != ''
  AND UPPER(TRIM(PRACTICE_NAME)) != 'PRACTICE_NAME'

UNION ALL

-- WOOLTRU GAUTENG: CITY often holds suburb/address fragments, appended to ADDRESS
SELECT
    'Gauteng',
    NULL, NULL, NULL, NULL,
    INITCAP(TRIM(PRACTICE_NAME)),
    TRIM(PRACTICE_NUM),
    'Pharmacy',
    INITCAP(TRIM(ARRAY_TO_STRING(
        [NULLIF(TRIM(ADDRESS), ''), NULLIF(TRIM(CITY), '')],
        ', '
    ))),
    TRIM(PHONE),
    'Private',
    'Wooltru',
    NULL
FROM RAW.PHARMACIES_WOOLTRU_GAUTENG
WHERE PRACTICE_NAME IS NOT NULL
  AND TRIM(PRACTICE_NAME) != ''
  AND UPPER(TRIM(PRACTICE_NAME)) NOT IN ('PRACTICE_NAME', 'PRACTICE NAME')

UNION ALL

-- WOOLTRU KZN
SELECT
    'Kwazulu-Natal',
    NULL, NULL, NULL, NULL,
    INITCAP(TRIM(PRACTICE_NAME)),
    TRIM(PRACTICE_NUM),
    'Pharmacy',
    INITCAP(TRIM(ARRAY_TO_STRING(
        [NULLIF(TRIM(ADDRESS), ''), NULLIF(TRIM(CITY), '')],
        ', '
    ))),
    TRIM(PHONE),
    'Private',
    'Wooltru',
    NULL
FROM RAW.PHARMACIES_WOOLTRU_KZN
WHERE PRACTICE_NAME IS NOT NULL
  AND TRIM(PRACTICE_NAME) != ''
  AND UPPER(TRIM(PRACTICE_NAME)) NOT IN ('PRACTICE_NAME', 'PRACTICE NAME')

UNION ALL

-- SAMWUMED: no PROVINCE column; inferred from known GP/KZN city lists.
-- CITY values that look like address fragments are filtered out.
SELECT
    CASE
        WHEN UPPER(TRIM(CITY)) IN (
            'JOHANNESBURG', 'JOHANNESBURG SOUTH', 'JOHANNESBURG CBD',
            'SANDTON', 'RANDBURG', 'ROODEPOORT', 'SOWETO',
            'CENTURION', 'PRETORIA', 'PRETORIA NORTH', 'PRETORIA WEST', 'PRETORIA EAST',
            'MIDRAND', 'KEMPTON PARK', 'BENONI', 'BOKSBURG',
            'GERMISTON', 'ALBERTON', 'SPRINGS', 'BRAKPAN',
            'EDENVALE', 'KRUGERSDORP', 'RANDFONTEIN', 'CARLETONVILLE',
            'VEREENIGING', 'VANDERBIJLPARK', 'HEIDELBERG', 'HEIDELBERG - GP',
            'NIGEL', 'BRONKHORSTSPRUIT', 'CULLINAN',
            'AKASIA', 'LENASIA', 'LENASIA SOUTH',
            'TEMBISA', 'KATLEHONG', 'DAVEYTON',
            'GA-RANKUWA', 'SOSHANGUVE', 'MABOPANE',
            'MAMELODI', 'ATTERIDGEVILLE', 'DIEPSLOOT', 'ALEXANDRA',
            'COSMO CITY', 'FOURWAYS', 'BRYANSTON',
            'BEDFORDVIEW', 'PRIMROSE',
            'HONEYDEW', 'FLORIDA',
            'WESTONARIA', 'FOCHVILLE', 'MEYERTON',
            'SEBOKENG', 'EVATON', 'ORANGE FARM',
            'VOSLOORUS', 'KAGISO', 'DOBSONVILLE',
            'MEADOWLANDS', 'DIEPKLOOF',
            'ELDORADOPARK', 'ENNERDALE',
            'MULBARTON', 'GLENVISTA', 'MONDEOR',
            'ROSETTENVILLE', 'TURFFONTEIN',
            'NORTHRIDING', 'NORTH RIDING', 'FERNDALE', 'NORTHCLIFF',
            'LINDEN', 'EMMARENTIA',
            'MORNINGSIDE', 'RIVONIA',
            'HALFWAY HOUSE', 'GLEN MARAIS',
            'GREENSTONE HILL',
            'BIRCHLEIGH',
            'IVORY PARK',
            'CLUBVIEW', 'WIERDAPARK',
            'LAUDIUM', 'WATERKLOOF',
            'HATFIELD', 'ARCADIA', 'SUNNYSIDE', 'GEZINA',
            'MONTANA', 'SINOVILLE', 'WONDERBOOM',
            'LYNNWOOD', 'MENLYN',
            'MORELETA PARK',
            'NORTHGATE',
            'MAGALIESBURG', 'HAMMANSKRAAL'
        ) THEN 'Gauteng'
        WHEN UPPER(TRIM(CITY)) IN (
            'DURBAN', 'DURBAN NORTH', 'DURBAN CENTRAL',
            'PIETERMARITZBURG',
            'NEWCASTLE', 'RICHARDS BAY',
            'PINETOWN', 'PHOENIX', 'CHATSWORTH',
            'AMANZIMTOTI', 'UMHLANGA',
            'BALLITO',
            'EMPANGENI', 'LADYSMITH', 'VRYHEID',
            'PORT SHEPSTONE', 'SHELLY BEACH', 'MARGATE', 'SOUTHBROOM', 'UVONGO',
            'SCOTTBURGH', 'PENNINGTON',
            'STANGER', 'KWADUKUZA',
            'TONGAAT', 'VERULAM', 'WESTVILLE',
            'KLOOF', 'HILLCREST', 'HOWICK',
            'ESTCOURT', 'DUNDEE', 'ESHOWE',
            'MTUBATUBA', 'KOKSTAD', 'GREYTOWN',
            'UMLAZI', 'KWAMASHU',
            'INANDA', 'ISIPINGO',
            'QUEENSBURGH', 'BLUFF', 'OVERPORT',
            'MUSGRAVE', 'SHALLCROSS',
            'MALVERN', 'MOUNT EDGECOMBE',
            'PONGOLA', 'JOZINI', 'HLUHLUWE',
            'NONGOMA', 'ULUNDI',
            'BERGVILLE', 'WINTERTON', 'MOOI RIVER',
            'GLENCOE', 'DANNHAUSER', 'MELMOTH',
            'NKANDLA', 'TUGELA FERRY', 'KRANSKOP', 'WARTBURG',
            'HAMMARSDALE', 'MPUMALANGA', 'UMZINTO',
            'UMKOMAAS', 'KINGSBURGH',
            'UMBILO', 'GLENWOOD', 'BEREA',
            'SYDENHAM',
            'LA LUCIA',
            'SHAKASKRAAL', 'SALT ROCK',
            'MTUNZINI', 'MANDENI',
            'NTUZUMA',
            'MEREBANK', 'WENTWORTH',
            'RESERVOIR HILLS',
            'SCOTTSVILLE',
            'HILTON', 'MPOPHOMENI',
            'EDENDALE', 'NORTHDALE',
            'IMBALI',
            'PAULPIETERSBURG',
            'MADADENI', 'OSIZWENI',
            'EZAKHENI',
            'NGWELEZANE',
            'ST LUCIA',
            'GINGINDLOVU',
            'PARK RYNIE', 'HIBBERDENE',
            'HARDING', 'UMZIMKHULU'
        ) THEN 'Kwazulu-Natal'
        ELSE NULL
    END,
    NULL, NULL, NULL, NULL,
    INITCAP(TRIM(PRACTICE_NAME)),
    TRIM(PRACTICE_NUM),
    'Pharmacy',
    INITCAP(TRIM(ARRAY_TO_STRING(
        [NULLIF(TRIM(ADDRESS), ''), NULLIF(TRIM(SUBURB), ''), NULLIF(TRIM(CITY), '')],
        ', '
    ))),
    TRIM(PHONE),
    'Private',
    'SAMWUMED',
    NULL
FROM RAW.PHARMACIES_SAMWUMED
WHERE PRACTICE_NAME IS NOT NULL
  AND TRIM(PRACTICE_NAME) != ''
  AND UPPER(TRIM(PRACTICE_NAME)) NOT IN ('PRACTICE_NAME', 'PRACTICE NAME')
  AND UPPER(TRIM(CITY)) NOT LIKE '%SHOP%'
  AND UPPER(TRIM(CITY)) NOT LIKE '%CENTRE%'
  AND UPPER(TRIM(CITY)) NOT LIKE '%MALL%'
  AND UPPER(TRIM(CITY)) NOT LIKE '%ROAD%'
  AND UPPER(TRIM(CITY)) NOT LIKE '%STREET%'
  AND UPPER(TRIM(CITY)) NOT LIKE '%AVENUE%'
  AND UPPER(TRIM(CITY)) NOT LIKE '%CNR%'
  AND UPPER(TRIM(CITY)) NOT LIKE '%BUILDING%'
  AND UPPER(TRIM(CITY)) NOT LIKE '%FLOOR%'
  AND CITY IS NOT NULL
  AND TRIM(CITY) != ''

UNION ALL

-- VITALITY WELLNESS: filtered to GP/KZN and pharmacy practice types
SELECT
    CASE
        WHEN UPPER(TRIM(PROVINCE)) LIKE '%GAUTENG%' THEN 'Gauteng'
        WHEN UPPER(TRIM(PROVINCE)) LIKE '%KWAZULU%' THEN 'Kwazulu-Natal'
        WHEN UPPER(TRIM(PROVINCE)) LIKE '%KZN%' THEN 'Kwazulu-Natal'
        ELSE NULL
    END,
    NULL, NULL, NULL, NULL,
    INITCAP(TRIM(PRACTICE_NAME)),
    NULL,
    'Pharmacy',
    INITCAP(TRIM(ARRAY_TO_STRING(
        [NULLIF(TRIM(ADDRESS), ''), NULLIF(TRIM(SUBURB), ''), NULLIF(TRIM(CITY), '')],
        ', '
    ))),
    TRIM(PHONE),
    'Private',
    'Vitality',
    NULL
FROM RAW.PHARMACIES_VITALITY_WELLNESS
WHERE PRACTICE_NAME IS NOT NULL
  AND TRIM(PRACTICE_NAME) != ''
  AND UPPER(TRIM(PRACTICE_NAME)) NOT IN ('PRACTICE_NAME', 'PRACTICE NAME')
  AND UPPER(TRIM(PRACTICE_TYPE)) LIKE '%PHARM%'
  AND (
      UPPER(TRIM(PROVINCE)) LIKE '%GAUTENG%'
      OR UPPER(TRIM(PROVINCE)) LIKE '%KWAZULU%'
      OR UPPER(TRIM(PROVINCE)) LIKE '%KZN%'
  );


-- STANDARDIZE PROVINCE NAMES
UPDATE INTERMEDIATE.PHARMACIES_COMBINED
SET PROVINCE = 'Gauteng'
WHERE UPPER(REPLACE(REPLACE(TRIM(PROVINCE), '-', ''), ' ', '')) = 'GAUTENG';

UPDATE INTERMEDIATE.PHARMACIES_COMBINED
SET PROVINCE = 'Kwazulu-Natal'
WHERE UPPER(REPLACE(REPLACE(TRIM(PROVINCE), '-', ''), ' ', '')) IN ('KZN', 'KWAZULUNATAL');


-- STANDARDIZE PRACTICE TYPE
UPDATE INTERMEDIATE.PHARMACIES_COMBINED
SET PRACTICE_TYPE = 'Pharmacy'
WHERE UPPER(PRACTICE_TYPE) IN ('PHARMACIES', 'PHARMACY', 'PHARM');


-- CLEAN PHONE NUMBERS: strip non-digits, keep first 10, NULL anything else
UPDATE INTERMEDIATE.PHARMACIES_COMBINED
SET PHONE = REGEXP_REPLACE(PHONE, r'[^0-9]', '')
WHERE PHONE IS NOT NULL;

UPDATE INTERMEDIATE.PHARMACIES_COMBINED
SET PHONE = LEFT(PHONE, 10)
WHERE PHONE IS NOT NULL
  AND LENGTH(PHONE) > 10;

UPDATE INTERMEDIATE.PHARMACIES_COMBINED
SET PHONE = NULL
WHERE PHONE IS NOT NULL
  AND LENGTH(PHONE) != 10;


-- CLEAN ADDRESS: normalize commas, whitespace, and stray punctuation
UPDATE INTERMEDIATE.PHARMACIES_COMBINED
SET ADDRESS = REGEXP_REPLACE(ADDRESS, r',\s*,', ',')
WHERE ADDRESS IS NOT NULL;

UPDATE INTERMEDIATE.PHARMACIES_COMBINED
SET ADDRESS = TRIM(TRIM(ADDRESS), ',')
WHERE ADDRESS IS NOT NULL;

UPDATE INTERMEDIATE.PHARMACIES_COMBINED
SET ADDRESS = REGEXP_REPLACE(ADDRESS, r'\s+', ' ')
WHERE ADDRESS IS NOT NULL;

UPDATE INTERMEDIATE.PHARMACIES_COMBINED
SET ADDRESS = TRIM(TRIM(ADDRESS), '.')
WHERE ADDRESS IS NOT NULL;

UPDATE INTERMEDIATE.PHARMACIES_COMBINED
SET ADDRESS = REGEXP_REPLACE(ADDRESS, r'\s*,\s*', ', ')
WHERE ADDRESS IS NOT NULL;

UPDATE INTERMEDIATE.PHARMACIES_COMBINED
SET ADDRESS = TRIM(ADDRESS)
WHERE ADDRESS IS NOT NULL;


-- CONSERVATIVE DEDUPLICATION USING PRACTICE_NUM
-- Dedupes on PRACTICE_NUM + COMPANY, keeping the longest ADDRESS.
-- Rows with NULL PRACTICE_NUM are all kept for spatial dedup post-geocoding.
-- Assigns PHARMACY_ID here.
CREATE OR REPLACE TABLE INTERMEDIATE.PHARMACIES_COMBINED AS
SELECT
    ROW_NUMBER() OVER (ORDER BY PROVINCE, PRACTICE_NAME, COMPANY) AS PHARMACY_ID,
    PROVINCE,
    LOCAL_MUNICIPALITY,
    DISTRICT_MUNICIPALITY,
    METROPOLITAN_MUNICIPALITY,
    CITY,
    PRACTICE_NAME,
    PRACTICE_NUM,
    PRACTICE_TYPE,
    ADDRESS,
    PHONE,
    FUNDING,
    COMPANY,
    COORDS
FROM (
    SELECT
        *,
        CASE
            WHEN PRACTICE_NUM IS NOT NULL THEN
                ROW_NUMBER() OVER (
                    PARTITION BY PRACTICE_NUM, COMPANY
                    ORDER BY LENGTH(ADDRESS) DESC, PRACTICE_NAME
                )
            ELSE 1
        END AS row_num
    FROM INTERMEDIATE.PHARMACIES_COMBINED
) t
WHERE row_num = 1;


DELETE FROM INTERMEDIATE.PHARMACIES_COMBINED
WHERE ADDRESS IS NULL
  AND PRACTICE_NUM IS NULL;


-- VALIDATION
SELECT PROVINCE, COUNT(*) AS RECORD_COUNT
FROM INTERMEDIATE.PHARMACIES_COMBINED
GROUP BY PROVINCE;

SELECT COMPANY, COUNT(*) AS RECORD_COUNT
FROM INTERMEDIATE.PHARMACIES_COMBINED
GROUP BY COMPANY
ORDER BY RECORD_COUNT DESC;

SELECT
    IF(PRACTICE_NUM IS NOT NULL, 'Has PRACTICE_NUM', 'NULL PRACTICE_NUM') AS PRACTICE_NUM_STATUS,
    COUNT(*) AS RECORD_COUNT
FROM INTERMEDIATE.PHARMACIES_COMBINED
GROUP BY PRACTICE_NUM_STATUS;

SELECT COUNT(*) AS TOTAL_RECORDS
FROM INTERMEDIATE.PHARMACIES_COMBINED;

SELECT *
FROM INTERMEDIATE.PHARMACIES_COMBINED
LIMIT 20;
