-- 03_fill_gaps_pharmacies.sql (BigQuery)
-- Populates missing PROVINCE using the lookup, then drops non-GP/KZN records.
-- Reads:  RAW.PROVINCE_LOOKUP, INTERMEDIATE.PHARMACIES_COMBINED
-- Writes: INTERMEDIATE.PHARMACIES_COMBINED (GP/KZN only), INTERMEDIATE.CITY_PROVINCE_LOOKUP (view)

-- MANUAL DATA CORRECTIONS
UPDATE INTERMEDIATE.PHARMACIES_COMBINED
SET PHONE = '0214888270'
WHERE PRACTICE_NUM = '1253085';

UPDATE INTERMEDIATE.PHARMACIES_COMBINED
SET ADDRESS = 'Shop 1, John Montague Centre, 19 Montague Dr, Montague Gardens, Cape Town, Western Cape, 7441.0, South Africa'
WHERE PRACTICE_NUM = '1253085';

UPDATE INTERMEDIATE.PHARMACIES_COMBINED
SET ADDRESS = 'Osborne Rd, Eshowe, KwaZulu-Natal, 3815'
WHERE PRACTICE_NUM = '819972';


-- STEP 1: STANDARDIZED LOOKUP VIEW (uppercase for matching)
CREATE OR REPLACE VIEW INTERMEDIATE.CITY_PROVINCE_LOOKUP AS
SELECT DISTINCT
    UPPER(TRIM(PROVINCE)) AS PROVINCE,
    NULLIF(UPPER(TRIM(LOCAL_MUNICIPALITY)), '') AS LOCAL_MUNICIPALITY,
    NULLIF(UPPER(TRIM(DISTRICT_MUNICIPALITY)), '') AS DISTRICT_MUNICIPALITY,
    NULLIF(UPPER(TRIM(METROPOLITAN_MUNICIPALITY)), '') AS METROPOLITAN_MUNICIPALITY,
    UPPER(TRIM(CITY)) AS CITY
FROM RAW.PROVINCE_LOOKUP
WHERE CITY IS NOT NULL
  AND TRIM(CITY) != '';


-- STEP 2: VERIFY LOOKUP CONTENTS
SELECT
    PROVINCE,
    COUNT(DISTINCT CITY) AS CITY_COUNT
FROM INTERMEDIATE.CITY_PROVINCE_LOOKUP
GROUP BY PROVINCE
ORDER BY PROVINCE;


-- STEP 3: BASELINE NULL PROVINCE COUNT
SELECT
    IF(PROVINCE IS NULL OR TRIM(PROVINCE) = '', 'MISSING PROVINCE', 'HAS PROVINCE') AS STATUS,
    COUNT(*) AS RECORD_COUNT
FROM INTERMEDIATE.PHARMACIES_COMBINED
GROUP BY STATUS;


-- STEP 4: HELPER COLUMN — last comma-separated ADDRESS segment
ALTER TABLE INTERMEDIATE.PHARMACIES_COMBINED
ADD COLUMN IF NOT EXISTS ADDRESS_LAST_SEGMENT STRING;

UPDATE INTERMEDIATE.PHARMACIES_COMBINED
SET ADDRESS_LAST_SEGMENT = UPPER(TRIM(ARRAY_REVERSE(SPLIT(ADDRESS, ','))[SAFE_OFFSET(0)]))
WHERE TRUE;


-- STEP 5: HELPER COLUMN — second-to-last segment (falls back to last when only one)
ALTER TABLE INTERMEDIATE.PHARMACIES_COMBINED
ADD COLUMN IF NOT EXISTS ADDRESS_SECOND_LAST STRING;

UPDATE INTERMEDIATE.PHARMACIES_COMBINED
SET ADDRESS_SECOND_LAST = UPPER(TRIM(COALESCE(
    ARRAY_REVERSE(SPLIT(ADDRESS, ','))[SAFE_OFFSET(1)],
    ARRAY_REVERSE(SPLIT(ADDRESS, ','))[SAFE_OFFSET(0)]
)))
WHERE TRUE;


-- STEPS 6-9 use MERGE: BigQuery rejects UPDATE...FROM when a target row matches
-- multiple source rows. Each MERGE picks one lookup match deterministically
-- (longest city name wins, then alphabetical).

-- STEP 6: PRIMARY MATCH on CITY column
MERGE INTERMEDIATE.PHARMACIES_COMBINED pc
USING (
    SELECT
        t.PHARMACY_ID,
        ARRAY_AGG(
            STRUCT(l.PROVINCE, l.LOCAL_MUNICIPALITY, l.DISTRICT_MUNICIPALITY, l.METROPOLITAN_MUNICIPALITY)
            ORDER BY LENGTH(l.CITY) DESC, l.CITY LIMIT 1
        )[OFFSET(0)] AS m
    FROM INTERMEDIATE.PHARMACIES_COMBINED t
    JOIN INTERMEDIATE.CITY_PROVINCE_LOOKUP l
      ON UPPER(TRIM(t.CITY)) = l.CITY
    WHERE t.PROVINCE IS NULL OR TRIM(t.PROVINCE) = ''
    GROUP BY t.PHARMACY_ID
) src
ON pc.PHARMACY_ID = src.PHARMACY_ID
WHEN MATCHED THEN UPDATE SET
    PROVINCE = src.m.PROVINCE,
    LOCAL_MUNICIPALITY = COALESCE(NULLIF(TRIM(pc.LOCAL_MUNICIPALITY), ''), src.m.LOCAL_MUNICIPALITY),
    DISTRICT_MUNICIPALITY = COALESCE(NULLIF(TRIM(pc.DISTRICT_MUNICIPALITY), ''), src.m.DISTRICT_MUNICIPALITY),
    METROPOLITAN_MUNICIPALITY = COALESCE(NULLIF(TRIM(pc.METROPOLITAN_MUNICIPALITY), ''), src.m.METROPOLITAN_MUNICIPALITY);


-- STEP 7: SECONDARY MATCH on last ADDRESS segment
MERGE INTERMEDIATE.PHARMACIES_COMBINED pc
USING (
    SELECT
        t.PHARMACY_ID,
        ARRAY_AGG(
            STRUCT(l.PROVINCE, l.LOCAL_MUNICIPALITY, l.DISTRICT_MUNICIPALITY, l.METROPOLITAN_MUNICIPALITY)
            ORDER BY LENGTH(l.CITY) DESC, l.CITY LIMIT 1
        )[OFFSET(0)] AS m
    FROM INTERMEDIATE.PHARMACIES_COMBINED t
    JOIN INTERMEDIATE.CITY_PROVINCE_LOOKUP l
      ON t.ADDRESS_LAST_SEGMENT = l.CITY
    WHERE t.PROVINCE IS NULL OR TRIM(t.PROVINCE) = ''
    GROUP BY t.PHARMACY_ID
) src
ON pc.PHARMACY_ID = src.PHARMACY_ID
WHEN MATCHED THEN UPDATE SET
    PROVINCE = src.m.PROVINCE,
    LOCAL_MUNICIPALITY = COALESCE(NULLIF(TRIM(pc.LOCAL_MUNICIPALITY), ''), src.m.LOCAL_MUNICIPALITY),
    DISTRICT_MUNICIPALITY = COALESCE(NULLIF(TRIM(pc.DISTRICT_MUNICIPALITY), ''), src.m.DISTRICT_MUNICIPALITY),
    METROPOLITAN_MUNICIPALITY = COALESCE(NULLIF(TRIM(pc.METROPOLITAN_MUNICIPALITY), ''), src.m.METROPOLITAN_MUNICIPALITY);


-- STEP 8: TERTIARY MATCH on second-to-last ADDRESS segment
MERGE INTERMEDIATE.PHARMACIES_COMBINED pc
USING (
    SELECT
        t.PHARMACY_ID,
        ARRAY_AGG(
            STRUCT(l.PROVINCE, l.LOCAL_MUNICIPALITY, l.DISTRICT_MUNICIPALITY, l.METROPOLITAN_MUNICIPALITY)
            ORDER BY LENGTH(l.CITY) DESC, l.CITY LIMIT 1
        )[OFFSET(0)] AS m
    FROM INTERMEDIATE.PHARMACIES_COMBINED t
    JOIN INTERMEDIATE.CITY_PROVINCE_LOOKUP l
      ON t.ADDRESS_SECOND_LAST = l.CITY
    WHERE t.PROVINCE IS NULL OR TRIM(t.PROVINCE) = ''
    GROUP BY t.PHARMACY_ID
) src
ON pc.PHARMACY_ID = src.PHARMACY_ID
WHEN MATCHED THEN UPDATE SET
    PROVINCE = src.m.PROVINCE,
    LOCAL_MUNICIPALITY = COALESCE(NULLIF(TRIM(pc.LOCAL_MUNICIPALITY), ''), src.m.LOCAL_MUNICIPALITY),
    DISTRICT_MUNICIPALITY = COALESCE(NULLIF(TRIM(pc.DISTRICT_MUNICIPALITY), ''), src.m.DISTRICT_MUNICIPALITY),
    METROPOLITAN_MUNICIPALITY = COALESCE(NULLIF(TRIM(pc.METROPOLITAN_MUNICIPALITY), ''), src.m.METROPOLITAN_MUNICIPALITY);


-- STEP 9: FALLBACK — city name (5+ chars) contained anywhere in ADDRESS
MERGE INTERMEDIATE.PHARMACIES_COMBINED pc
USING (
    SELECT
        t.PHARMACY_ID,
        ARRAY_AGG(
            STRUCT(l.PROVINCE, l.LOCAL_MUNICIPALITY, l.DISTRICT_MUNICIPALITY, l.METROPOLITAN_MUNICIPALITY)
            ORDER BY LENGTH(l.CITY) DESC, l.CITY LIMIT 1
        )[OFFSET(0)] AS m
    FROM INTERMEDIATE.PHARMACIES_COMBINED t
    JOIN INTERMEDIATE.CITY_PROVINCE_LOOKUP l
      ON UPPER(t.ADDRESS) LIKE '%' || l.CITY || '%'
     AND LENGTH(l.CITY) >= 5
    WHERE t.PROVINCE IS NULL OR TRIM(t.PROVINCE) = ''
    GROUP BY t.PHARMACY_ID
) src
ON pc.PHARMACY_ID = src.PHARMACY_ID
WHEN MATCHED THEN UPDATE SET
    PROVINCE = src.m.PROVINCE,
    LOCAL_MUNICIPALITY = COALESCE(NULLIF(TRIM(pc.LOCAL_MUNICIPALITY), ''), src.m.LOCAL_MUNICIPALITY),
    DISTRICT_MUNICIPALITY = COALESCE(NULLIF(TRIM(pc.DISTRICT_MUNICIPALITY), ''), src.m.DISTRICT_MUNICIPALITY),
    METROPOLITAN_MUNICIPALITY = COALESCE(NULLIF(TRIM(pc.METROPOLITAN_MUNICIPALITY), ''), src.m.METROPOLITAN_MUNICIPALITY);


-- STEP 10: STANDARDIZE PROVINCE NAMES
UPDATE INTERMEDIATE.PHARMACIES_COMBINED
SET PROVINCE = 'Gauteng'
WHERE UPPER(TRIM(PROVINCE)) = 'GAUTENG';

UPDATE INTERMEDIATE.PHARMACIES_COMBINED
SET PROVINCE = 'KwaZulu-Natal'
WHERE UPPER(TRIM(PROVINCE)) IN ('KWAZULU-NATAL', 'KWAZULU NATAL', 'KZN');


-- STEP 11: VERIFICATION BEFORE DELETION
SELECT
    IF(PROVINCE IS NULL OR TRIM(PROVINCE) = '', 'NULL/EMPTY (TO BE DROPPED)', PROVINCE) AS PROVINCE_STATUS,
    COUNT(*) AS RECORD_COUNT,
    ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER(), 2) AS PERCENTAGE
FROM INTERMEDIATE.PHARMACIES_COMBINED
GROUP BY PROVINCE_STATUS
ORDER BY RECORD_COUNT DESC;


-- STEP 12: SAMPLE RECORDS THAT WILL BE DROPPED
SELECT
    PHARMACY_ID,
    PRACTICE_NAME,
    ADDRESS,
    CITY,
    ADDRESS_LAST_SEGMENT,
    ADDRESS_SECOND_LAST
FROM INTERMEDIATE.PHARMACIES_COMBINED
WHERE PROVINCE IS NULL OR TRIM(PROVINCE) = ''
ORDER BY RAND();


-- STEP 13: DROP NON-GP/KZN RECORDS
DELETE FROM INTERMEDIATE.PHARMACIES_COMBINED
WHERE PROVINCE IS NULL
   OR TRIM(PROVINCE) = ''
   OR UPPER(TRIM(PROVINCE)) NOT IN ('GAUTENG', 'KWAZULU-NATAL');


-- STEP 14: DROP HELPER COLUMNS
ALTER TABLE INTERMEDIATE.PHARMACIES_COMBINED
DROP COLUMN IF EXISTS ADDRESS_LAST_SEGMENT;

ALTER TABLE INTERMEDIATE.PHARMACIES_COMBINED
DROP COLUMN IF EXISTS ADDRESS_SECOND_LAST;


-- STEP 15: FINAL VERIFICATION
SELECT
    PROVINCE,
    COUNT(*) AS TOTAL_RECORDS,
    COUNT(DISTINCT PRACTICE_NUM) AS UNIQUE_PRACTICES,
    SUM(IF(CITY IS NULL OR TRIM(CITY) = '', 1, 0)) AS NULL_CITY_COUNT,
    SUM(IF(COORDS IS NULL, 1, 0)) AS NULL_COORDS_COUNT
FROM INTERMEDIATE.PHARMACIES_COMBINED
GROUP BY PROVINCE
ORDER BY PROVINCE;


-- STEP 16: SUMMARY
SELECT 'TOTAL GP/KZN PHARMACIES' AS METRIC, COUNT(*) AS VALUE
FROM INTERMEDIATE.PHARMACIES_COMBINED
UNION ALL
SELECT 'GAUTENG COUNT', COUNT(*)
FROM INTERMEDIATE.PHARMACIES_COMBINED
WHERE PROVINCE = 'Gauteng'
UNION ALL
SELECT 'KWAZULU-NATAL COUNT', COUNT(*)
FROM INTERMEDIATE.PHARMACIES_COMBINED
WHERE PROVINCE = 'KwaZulu-Natal'
UNION ALL
SELECT 'NEEDING GEOCODING', COUNT(*)
FROM INTERMEDIATE.PHARMACIES_COMBINED
WHERE COORDS IS NULL;
