-- 04_deduplicate_pharmacies.sql (BigQuery)
-- Dedupes records WITH PRACTICE_NUM on PRACTICE_NUM + PROVINCE, keeping the longest
-- name/address and aggregating source networks. Records WITHOUT PRACTICE_NUM are
-- preserved for spatial deduplication post-geocoding.
-- Output: INTERMEDIATE.PHARMACIES_DEDUPLICATED

CREATE OR REPLACE TABLE INTERMEDIATE.PHARMACIES_DEDUPLICATED AS

SELECT
    PROVINCE,
    LOCAL_MUNICIPALITY,
    DISTRICT_MUNICIPALITY,
    METROPOLITAN_MUNICIPALITY,
    CITY,
    MAX_BY(PRACTICE_NAME, LENGTH(PRACTICE_NAME)) AS PRACTICE_NAME,
    PRACTICE_NUM,
    'Pharmacy' AS PRACTICE_TYPE,
    MAX_BY(ADDRESS, LENGTH(ADDRESS)) AS ADDRESS,
    MAX(PHONE) AS PHONE,
    'Private' AS FUNDING,
    STRING_AGG(DISTINCT COMPANY, ', ' ORDER BY COMPANY) AS COMPANIES,
    COUNT(DISTINCT COMPANY) AS NETWORK_COUNT,
    CAST(NULL AS GEOGRAPHY) AS COORDS
FROM INTERMEDIATE.PHARMACIES_COMBINED
WHERE PRACTICE_NUM IS NOT NULL
GROUP BY PRACTICE_NUM, PROVINCE, LOCAL_MUNICIPALITY, DISTRICT_MUNICIPALITY, METROPOLITAN_MUNICIPALITY, CITY

UNION ALL

SELECT
    PROVINCE,
    LOCAL_MUNICIPALITY,
    DISTRICT_MUNICIPALITY,
    METROPOLITAN_MUNICIPALITY,
    CITY,
    PRACTICE_NAME,
    NULL AS PRACTICE_NUM,
    PRACTICE_TYPE,
    ADDRESS,
    PHONE,
    FUNDING,
    COMPANY AS COMPANIES,
    1 AS NETWORK_COUNT,
    COORDS
FROM INTERMEDIATE.PHARMACIES_COMBINED
WHERE PRACTICE_NUM IS NULL;


-- VALIDATION
SELECT
    IF(PRACTICE_NUM IS NOT NULL, 'Has PRACTICE_NUM', 'NULL PRACTICE_NUM') AS PRACTICE_NUM_STATUS,
    COUNT(*) AS RECORD_COUNT
FROM INTERMEDIATE.PHARMACIES_DEDUPLICATED
GROUP BY PRACTICE_NUM_STATUS;

SELECT
    NETWORK_COUNT,
    COUNT(*) AS PHARMACY_COUNT
FROM INTERMEDIATE.PHARMACIES_DEDUPLICATED
WHERE PRACTICE_NUM IS NOT NULL
GROUP BY NETWORK_COUNT
ORDER BY NETWORK_COUNT;

SELECT COUNT(*) AS TOTAL_RECORDS
FROM INTERMEDIATE.PHARMACIES_DEDUPLICATED;
