-- 05_add_hospitals.sql (BigQuery)
-- Appends public hospital records from RAW.PHARMACIES_HOSPITALS to
-- INTERMEDIATE.PHARMACIES_COMBINED with PRACTICE_TYPE='Hospital', FUNDING='Public'.
-- COORDS built from X (longitude) / Y (latitude), EPSG:4326.

DECLARE max_pharmacy_id INT64 DEFAULT (
    SELECT COALESCE(MAX(PHARMACY_ID), 0)
    FROM INTERMEDIATE.PHARMACIES_COMBINED
);

INSERT INTO INTERMEDIATE.PHARMACIES_COMBINED (
    PHARMACY_ID,
    PROVINCE,
    LOCAL_MUNICIPALITY,
    DISTRICT_MUNICIPALITY,
    METROPOLITAN_MUNICIPALITY,
    CITY,
    PRACTICE_NAME,
    PRACTICE_NUM,
    PRACTICE_TYPE,
    ADDRESS,
    PHONE,
    FUNDING,
    COMPANY,
    COORDS
)
SELECT
    max_pharmacy_id + ROW_NUMBER() OVER (ORDER BY NAME) AS PHARMACY_ID,
    PR_NAME AS PROVINCE,
    NULL AS LOCAL_MUNICIPALITY,
    -- DC_MDB_C codes starting with 'DC' are district municipalities; others are metros
    IF(DC_MDB_C LIKE 'DC%', DC_NAME, NULL) AS DISTRICT_MUNICIPALITY,
    IF(DC_MDB_C NOT LIKE 'DC%', MAP_TITLE, NULL) AS METROPOLITAN_MUNICIPALITY,
    NULL AS CITY,
    NAME AS PRACTICE_NAME,
    NULL AS PRACTICE_NUM,
    'Hospital' AS PRACTICE_TYPE,
    NULL AS ADDRESS,
    NULL AS PHONE,
    'Public' AS FUNDING,
    NULL AS COMPANY,
    ST_GEOGPOINT(X, Y) AS COORDS
FROM RAW.PHARMACIES_HOSPITALS
WHERE PR_NAME IN ('Gauteng', 'KwaZulu-Natal');


ALTER TABLE INTERMEDIATE.PHARMACIES_COMBINED
ADD COLUMN IF NOT EXISTS SAPC_ID STRING;


-- VALIDATION
SELECT
    PROVINCE,
    COUNT(*) AS HOSPITAL_COUNT
FROM INTERMEDIATE.PHARMACIES_COMBINED
WHERE PRACTICE_TYPE = 'Hospital'
GROUP BY PROVINCE
ORDER BY PROVINCE;

SELECT
    PRACTICE_TYPE,
    FUNDING,
    COUNT(*) AS RECORD_COUNT
FROM INTERMEDIATE.PHARMACIES_COMBINED
GROUP BY PRACTICE_TYPE, FUNDING
ORDER BY PRACTICE_TYPE, FUNDING;

SELECT COUNT(*) AS TOTAL_RECORDS
FROM INTERMEDIATE.PHARMACIES_COMBINED;
